# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orchestrator_agent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'orchestrator_agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18orchestrator_agent.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x8a\x01\n\x14OrchestrationRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x33\n\x07\x63ontext\x18\x02 \x03(\x0b\x32\".OrchestrationRequest.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"f\n\x15OrchestrationResponse\x12)\n\x08response\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x32T\n\x13OrchestratorService\x12=\n\x0cProcessQuery\x12\x15.OrchestrationRequest\x1a\x16.OrchestrationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orchestrator_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORCHESTRATIONREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_ORCHESTRATIONREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_ORCHESTRATIONREQUEST']._serialized_start=59
  _globals['_ORCHESTRATIONREQUEST']._serialized_end=197
  _globals['_ORCHESTRATIONREQUEST_CONTEXTENTRY']._serialized_start=151
  _globals['_ORCHESTRATIONREQUEST_CONTEXTENTRY']._serialized_end=197
  _globals['_ORCHESTRATIONRESPONSE']._serialized_start=199
  _globals['_ORCHESTRATIONRESPONSE']._serialized_end=301
  _globals['_ORCHESTRATORSERVICE']._serialized_start=303
  _globals['_ORCHESTRATORSERVICE']._serialized_end=387
# @@protoc_insertion_point(module_scope)
