# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings
from qa_system_with_a2a_demo.agents.rag_agent import rag_agent_pb2 as rag__agent__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rag_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagAgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDocument = channel.unary_unary(
                '/RagAgentService/ProcessDocument',
                request_serializer=rag__agent__pb2.FileUpload.SerializeToString,
                response_deserializer=rag__agent__pb2.ChunkResponse.FromString,
                _registered_method=True)
        self.RetrieveChunks = channel.unary_unary(
                '/RagAgentService/RetrieveChunks',
                request_serializer=rag__agent__pb2.ChunkRequest.SerializeToString,
                response_deserializer=rag__agent__pb2.ChunkResponse.FromString,
                _registered_method=True)


class RagAgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDocument,
                    request_deserializer=rag__agent__pb2.FileUpload.FromString,
                    response_serializer=rag__agent__pb2.ChunkResponse.SerializeToString,
            ),
            'RetrieveChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveChunks,
                    request_deserializer=rag__agent__pb2.ChunkRequest.FromString,
                    response_serializer=rag__agent__pb2.ChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RagAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RagAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagAgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RagAgentService/ProcessDocument',
            rag__agent__pb2.FileUpload.SerializeToString,
            rag__agent__pb2.ChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RagAgentService/RetrieveChunks',
            rag__agent__pb2.ChunkRequest.SerializeToString,
            rag__agent__pb2.ChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
