# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag_agent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'rag_agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frag_agent.proto\"/\n\nFileUpload\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\",\n\x0c\x43hunkRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"\x80\x01\n\rChunkResponse\x12\x0e\n\x06\x63hunks\x18\x01 \x03(\t\x12.\n\x08metadata\x18\x02 \x03(\x0b\x32\x1c.ChunkResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32r\n\x0fRagAgentService\x12.\n\x0fProcessDocument\x12\x0b.FileUpload\x1a\x0e.ChunkResponse\x12/\n\x0eRetrieveChunks\x12\r.ChunkRequest\x1a\x0e.ChunkResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNKRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_CHUNKRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_FILEUPLOAD']._serialized_start=19
  _globals['_FILEUPLOAD']._serialized_end=66
  _globals['_CHUNKREQUEST']._serialized_start=68
  _globals['_CHUNKREQUEST']._serialized_end=112
  _globals['_CHUNKRESPONSE']._serialized_start=115
  _globals['_CHUNKRESPONSE']._serialized_end=243
  _globals['_CHUNKRESPONSE_METADATAENTRY']._serialized_start=196
  _globals['_CHUNKRESPONSE_METADATAENTRY']._serialized_end=243
  _globals['_RAGAGENTSERVICE']._serialized_start=245
  _globals['_RAGAGENTSERVICE']._serialized_end=359
# @@protoc_insertion_point(module_scope)
